In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("uciml/breast-cancer-wisconsin-data")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'breast-cancer-wisconsin-data' dataset.
Path to dataset files: /kaggle/input/breast-cancer-wisconsin-data

In [ ]:
import warnings
warnings.filterwarnings("ignore")

In [ ]:
import os
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df=pd.read_csv(os.path.join(path,'data.csv'))

In [ ]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [ ]:
pd.set_option('display.max_columns',None)
pd.set_option('display.float_format',lambda x:f'{x:.4f}')
np.set_printoptions(suppress=True)

In [ ]:
# M = Malignant → cancerous tumor
# B = Benign → non-cancerous tumor

df.shape

(569, 33)

In [ ]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [ ]:
df.columns=df.columns.str.strip()

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    object
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
 32  Unnamed: 32              0 non-null      float64
dtypes: float64(31), int64(1), object(1)
memory usage: 146.8+ KB

In [ ]:
df.drop(['id','Unnamed: 32'],axis=1,inplace=True)

In [ ]:
df['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [ ]:
# if you want to see target column distributon in percentage then

df['diagnosis'].value_counts(normalize=True)*100

diagnosis
B   62.7417
M   37.2583
Name: proportion, dtype: float64

In [ ]:
# convert the targte categorical column into integer

df['diagnosis']=df['diagnosis'].map({
    'M':1,
    'B':0
}).astype(int)

In [ ]:
df['diagnosis'].value_counts()

diagnosis
0    357
1    212
Name: count, dtype: int64

In [ ]:
#split the data

X=df.drop('diagnosis',axis=1)
y=df['diagnosis']

In [ ]:
df.shape

(569, 31)

In [ ]:
#train test split
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [ ]:
# StandardScaling

from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

In [ ]:
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [ ]:
# classification models

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score,recall_score

models = {
    "LogisticRegression": LogisticRegression(),
    "NaiveBayes": GaussianNB(),
    "RandomForest": RandomForestClassifier(),
    "DecisionTree": DecisionTreeClassifier()
}

for name,model in models.items():
  print(name)

  model.fit(X_train_scaled,y_train)

  y_pred=model.predict(X_test_scaled)

  print("Accuracy: ",accuracy_score(y_test,y_pred))
  print("Recall: ",recall_score(y_test,y_pred))
  print("*"*30)
  print()

LogisticRegression
Accuracy:  0.9649122807017544
Recall:  0.9285714285714286
******************************

NaiveBayes
Accuracy:  0.9210526315789473
Recall:  0.8571428571428571
******************************

RandomForest
Accuracy:  0.9736842105263158
Recall:  0.9285714285714286
******************************

DecisionTree
Accuracy:  0.9298245614035088
Recall:  0.8809523809523809
******************************

In [ ]:
# seleting random forest and logistic regresion

params = {

    "LogisticRegression": {
        "C": [0.01, 0.1, 10, 0.001],
        "penalty": ['l1', 'l2', 'elasticnet'],
        "solver": ['liblinear', 'saga', 'lbfgs']
    },

    "RandomForest": {
        "n_estimators": [50, 100, 200],
        "max_depth": [None, 5, 10, 20],
        "min_samples_split": [2, 5, 10],
        "min_samples_leaf": [1, 2, 4],
        "max_features": ['sqrt', 'log2']
    }

}

models={
    "LogisticRegression": LogisticRegression(),
    "RandomForest": RandomForestClassifier(),
}


from sklearn.model_selection import GridSearchCV

best_models={}

for name,model in models.items():

  print(name)

  grid=GridSearchCV(estimator=model,param_grid=params[name],cv=5,scoring='recall')

  grid.fit(X_train_scaled,y_train)

  best_models[name]=grid

  print("best parameter:",grid.best_params_)
  print("best cv accuracy:",grid.best_score_)

  y_pred=grid.predict(X_test_scaled)

  print("Accuracy: ",accuracy_score(y_test,y_pred))
  print("Recall: ",recall_score(y_test,y_pred))
  print("*"*30)

LogisticRegression
best parameter: {'C': 0.1, 'penalty': 'l1', 'solver': 'liblinear'}
best cv accuracy: 0.9529411764705882
Accuracy:  0.9824561403508771
Recall:  0.9523809523809523
******************************
RandomForest
best parameter: {'max_depth': None, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 200}
best cv accuracy: 0.9411764705882353
Accuracy:  0.9736842105263158
Recall:  0.9285714285714286
******************************

In [ ]:
model=LogisticRegression(C=0.1,penalty='l1',solver='liblinear')

model.fit(X_train_scaled,y_train)

LogisticRegression(C=0.1, penalty='l1', solver='liblinear')

In [ ]:
model

LogisticRegression(C=0.1, penalty='l1', solver='liblinear')

In [ ]:
new_data = pd.DataFrame([{
    'radius_mean': 14.0,
    'texture_mean': 17.5,
    'perimeter_mean': 90.0,
    'area_mean': 600.0,
    'smoothness_mean': 0.10,
    'compactness_mean': 0.12,
    'concavity_mean': 0.10,
    'concave points_mean': 0.06,
    'symmetry_mean': 0.18,
    'fractal_dimension_mean': 0.06,

    'radius_se': 0.30,
    'texture_se': 1.20,
    'perimeter_se': 2.00,
    'area_se': 25.0,
    'smoothness_se': 0.007,
    'compactness_se': 0.03,
    'concavity_se': 0.03,
    'concave points_se': 0.01,
    'symmetry_se': 0.02,
    'fractal_dimension_se': 0.004,

    'radius_worst': 16.0,
    'texture_worst': 22.0,
    'perimeter_worst': 105.0,
    'area_worst': 800.0,
    'smoothness_worst': 0.14,
    'compactness_worst': 0.25,
    'concavity_worst': 0.30,
    'concave points_worst': 0.12,
    'symmetry_worst': 0.30,
    'fractal_dimension_worst': 0.08
}])

In [ ]:
new_data

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,14.0000,17.5000,90.0000,600.0000,0.1000,0.1200,0.1000,0.0600,0.1800,0.0600,0.3000,1.2000,2.0000,25.0000,0.0070,0.0300,0.0300,0.0100,0.0200,0.0040,16.0000,22.0000,105.0000,800.0000,0.1400,0.2500,0.3000,0.1200,0.3000,0.0800

In [ ]:
new_data_scaled=scaler.transform(new_data)

In [ ]:
new_data_scaled

array([[-0.04645319, -0.44743846, -0.08974781, -0.16548482,  0.28033209,
         0.30018301,  0.13253228,  0.27711288, -0.05421317, -0.38989497,
        -0.38358456, -0.03241222, -0.42982621, -0.33682546,  0.03673447,
         0.26564363, -0.06365638, -0.26910589, -0.05140051,  0.08898928,
        -0.07180137, -0.64300631, -0.08379069, -0.15569592,  0.33753319,
        -0.0349467 ,  0.11723205,  0.06753438,  0.13713999, -0.22721725]])

In [ ]:
model

LogisticRegression(C=0.1, penalty='l1', solver='liblinear')

In [ ]:
new_data_pred=model.predict(new_data_scaled)

In [ ]:
print(new_data_pred)

[0]

In [ ]:
X_train_scaled

array([[ 0.51855873,  0.89182579,  0.4246317 , ..., -0.23574392,
         0.05456632,  0.02183673],
       [-0.51636409, -1.63971029, -0.54134872, ..., -0.32320788,
        -0.13757624, -0.90440164],
       [-0.36811839,  0.45551496, -0.38824993, ..., -0.89082504,
        -0.675893  , -0.14401559],
       ...,
       [-0.32616206,  1.33280304, -0.38905998, ..., -0.84289958,
        -0.96490082, -1.16888375],
       [ 0.00948859,  0.25952507,  0.00786279, ...,  0.27571059,
        -0.60284707, -0.30545988],
       [ 0.80945595,  0.36918608,  0.79320285, ...,  1.00657384,
        -0.46151907, -0.44817001]])

In [ ]:
!pip install keras-tuner

Collecting keras-tuner
  Downloading keras_tuner-1.4.8-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (26.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (2.32.4)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: grpcio in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (1.83.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.13/dist-packages (from grpcio->keras-tuner) (4.16.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (2.1.3)
Requirement already satisfied: rich in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (0.20.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (0.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->keras-tuner) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->keras-tuner) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->keras-tuner) (2026.7.22)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich->keras->keras-tuner) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich->keras->keras-tuner) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.8-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 3.2 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.8 kt-legacy-1.0.5

In [ ]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Dropout
import keras_tuner as kt

def build_model(hp):

    model = Sequential()

    counter = 0

    for i in range(hp.Int('layers', min_value=1, max_value=10)):

        if counter == 0:
            model.add(Dense(
                hp.Int('neurons' + str(i), min_value=8, max_value=128),
                activation=hp.Choice(
                    'activation' + str(i),
                    values=['sigmoid', 'relu', 'tanh']
                ),
                input_dim=X_train.shape[1]
            ))
        else:
            model.add(Dense(
                hp.Int('neurons' + str(i), min_value=8, max_value=128),
                activation=hp.Choice(
                    'activation' + str(i),
                    values=['sigmoid', 'relu', 'tanh']
                )
            ))

        # Dropout hyperparameter
        model.add(
            Dropout(
                hp.Float(
                    'dropout_' + str(i),
                    min_value=0.0,
                    max_value=0.5,
                    step=0.1
                )
            )
        )

        counter += 1

    # Output layer
    model.add(Dense(1, activation='sigmoid'))

    model.compile(
        optimizer=hp.Choice(
            'optimizer',
            values=['adam', 'sgd', 'rmsprop', 'adagrad']
        ),
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

In [ ]:
tuner=kt.RandomSearch(build_model,
                      objective='val_accuracy',
                      max_trials=10,
                      directory='new3')

In [ ]:
tuner.search(X_train_scaled,y_train,epochs=50,validation_split=0.2)

Trial 10 Complete [00h 00m 13s]
val_accuracy: 0.9890109896659851

Best val_accuracy So Far: 0.9890109896659851
Total elapsed time: 00h 02m 06s

In [ ]:
ann_model=tuner.get_best_models(num_models=1)[0]

In [ ]:
ann_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 90)             │         2,790 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 90)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 45)             │         4,095 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 45)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 47)             │         2,162 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 47)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            48 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9,095 (35.53 KB)

 Trainable params: 9,095 (35.53 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
new_data = pd.DataFrame([{
    'radius_mean': 14.0,
    'texture_mean': 17.5,
    'perimeter_mean': 90.0,
    'area_mean': 600.0,
    'smoothness_mean': 0.10,
    'compactness_mean': 0.12,
    'concavity_mean': 0.10,
    'concave points_mean': 0.06,
    'symmetry_mean': 0.18,
    'fractal_dimension_mean': 0.06,

    'radius_se': 0.30,
    'texture_se': 1.20,
    'perimeter_se': 2.00,
    'area_se': 25.0,
    'smoothness_se': 0.007,
    'compactness_se': 0.03,
    'concavity_se': 0.03,
    'concave points_se': 0.01,
    'symmetry_se': 0.02,
    'fractal_dimension_se': 0.004,

    'radius_worst': 16.0,
    'texture_worst': 22.0,
    'perimeter_worst': 105.0,
    'area_worst': 800.0,
    'smoothness_worst': 0.14,
    'compactness_worst': 0.25,
    'concavity_worst': 0.30,
    'concave points_worst': 0.12,
    'symmetry_worst': 0.30,
    'fractal_dimension_worst': 0.08
}])

In [ ]:
new_data_scaled=scaler.transform(new_data)

In [ ]:
new_data_scaled

array([[-0.04645319, -0.44743846, -0.08974781, -0.16548482,  0.28033209,
         0.30018301,  0.13253228,  0.27711288, -0.05421317, -0.38989497,
        -0.38358456, -0.03241222, -0.42982621, -0.33682546,  0.03673447,
         0.26564363, -0.06365638, -0.26910589, -0.05140051,  0.08898928,
        -0.07180137, -0.64300631, -0.08379069, -0.15569592,  0.33753319,
        -0.0349467 ,  0.11723205,  0.06753438,  0.13713999, -0.22721725]])

In [ ]:
new_data_pred=ann_model.predict(new_data_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step

In [ ]:
print("ann model prediction: ",new_data_pred)

ann model prediction:  [[0.00323661]]

In [ ]:
if new_data_pred >= 0.5:
    print("Prediction:", 1)
    print("Diagnosis: Malignant")
    print("Probability:", new_data_pred)
else:
    print("Prediction:", 0)
    print("Diagnosis: Benign")
    print("Probability:", new_data_pred)

Prediction: 0
Diagnosis: Benign
Probability: [[0.00323661]]

In [ ]:
model

LogisticRegression(C=0.1, penalty='l1', solver='liblinear')

In [ ]:
import joblib

joblib.dump(scaler,'scaler.pkl',compress=3)
joblib.dump(model,'logistic_regression_model.pkl',compress=3)

ann_model.save('ann_model.keras')

In [ ]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,1,17.9900,10.3800,122.8000,1001.0000,0.1184,0.2776,0.3001,0.1471,0.2419,0.0787,1.0950,0.9053,8.5890,153.4000,0.0064,0.0490,0.0537,0.0159,0.0300,0.0062,25.3800,17.3300,184.6000,2019.0000,0.1622,0.6656,0.7119,0.2654,0.4601,0.1189
1,1,20.5700,17.7700,132.9000,1326.0000,0.0847,0.0786,0.0869,0.0702,0.1812,0.0567,0.5435,0.7339,3.3980,74.0800,0.0052,0.0131,0.0186,0.0134,0.0139,0.0035,24.9900,23.4100,158.8000,1956.0000,0.1238,0.1866,0.2416,0.1860,0.2750,0.0890
2,1,19.6900,21.2500,130.0000,1203.0000,0.1096,0.1599,0.1974,0.1279,0.2069,0.0600,0.7456,0.7869,4.5850,94.0300,0.0062,0.0401,0.0383,0.0206,0.0225,0.0046,23.5700,25.5300,152.5000,1709.0000,0.1444,0.4245,0.4504,0.2430,0.3613,0.0876
3,1,11.4200,20.3800,77.5800,386.1000,0.1425,0.2839,0.2414,0.1052,0.2597,0.0974,0.4956,1.1560,3.4450,27.2300,0.0091,0.0746,0.0566,0.0187,0.0596,0.0092,14.9100,26.5000,98.8700,567.7000,0.2098,0.8663,0.6869,0.2575,0.6638,0.1730
4,1,20.2900,14.3400,135.1000,1297.0000,0.1003,0.1328,0.1980,0.1043,0.1809,0.0588,0.7572,0.7813,5.4380,94.4400,0.0115,0.0246,0.0569,0.0188,0.0176,0.0051,22.5400,16.6700,152.2000,1575.0000,0.1374,0.2050,0.4000,0.1625,0.2364,0.0768

In [ ]:
df.head(2)

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,1,17.9900,10.3800,122.8000,1001.0000,0.1184,0.2776,0.3001,0.1471,0.2419,0.0787,1.0950,0.9053,8.5890,153.4000,0.0064,0.0490,0.0537,0.0159,0.0300,0.0062,25.3800,17.3300,184.6000,2019.0000,0.1622,0.6656,0.7119,0.2654,0.4601,0.1189
1,1,20.5700,17.7700,132.9000,1326.0000,0.0847,0.0786,0.0869,0.0702,0.1812,0.0567,0.5435,0.7339,3.3980,74.0800,0.0052,0.0131,0.0186,0.0134,0.0139,0.0035,24.9900,23.4100,158.8000,1956.0000,0.1238,0.1866,0.2416,0.1860,0.2750,0.0890