<a href="https://colab.research.google.com/github/azrapatvi/dl-practice/blob/main/1_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [ ]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],

    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],

    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],

    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [ ]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [ ]:
X=df.drop('needs_water',axis=1)
y=df['needs_water']

In [ ]:
# # we have to doo minmax scaling herre in dl (normalization) in normalization w put the values in between 0 - 1
# wwhile in standard scaler we make means =0 and std deviation =1

from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()

In [ ]:
df['needs_water'].value_counts()

needs_water
1    8
0    8
Name: count, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [ ]:
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [ ]:
X_train.shape[1]

3

In [ ]:
from tensorflow.keras import Sequential,layers,Input

model=Sequential([
    layers.Input(shape=(X_train.shape[1],)), #input layer
    layers.Dense(8,activation='relu'), #hidden layer
    layers.Dense(1,activation='sigmoid') #output layer
])

In [ ]:
model

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 8)              │            32 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 41 (164.00 B)

 Trainable params: 41 (164.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(optimizer='sgd',loss='binary_crossentropy',metrics=['accuracy']) # sets up the rules for backpropagation and when you do mode.fit thenn it will useee thiss in backpropagation

In [ ]:
X_train_scaled

array([[0.29333333, 0.84615385, 0.875     ],
       [0.        , 0.15384615, 0.125     ],
       [0.46666667, 0.46153846, 0.5       ],
       [0.06666667, 0.92307692, 0.625     ],
       [0.17333333, 0.        , 0.75      ],
       [0.86666667, 0.23076923, 0.25      ],
       [1.        , 0.84615385, 0.625     ],
       [0.73333333, 0.61538462, 0.75      ],
       [0.53333333, 1.        , 1.        ],
       [0.26666667, 0.        , 0.        ],
       [0.2       , 0.30769231, 0.375     ],
       [0.33333333, 0.53846154, 0.625     ]])

In [ ]:
# train the neural netowrokk

history=model.fit(
    X_train_scaled,
    y_train,
    epochs=100,
    batch_size=4,
    verbose=1,
    validation_split=0.2
)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 82ms/step - accuracy: 0.6667 - loss: 0.6359 - val_accuracy: 0.3333 - val_loss: 0.7277
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 0.6355 - val_accuracy: 0.3333 - val_loss: 0.7265
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6667 - loss: 0.6355 - val_accuracy: 0.3333 - val_loss: 0.7282
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 0.6344 - val_accuracy: 0.3333 - val_loss: 0.7301
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 0.6325 - val_accuracy: 0.3333 - val_loss: 0.7319
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.6320 - val_accuracy: 0.3333 - val_loss: 0.7337
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.6311 - val_accuracy: 0.3333 - val_loss: 0.7354
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 0.6298 - val_accuracy: 0.3333 - val_loss: 0.7347
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6667 - loss: 0.6296 - val_accuracy: 0.3333 - val_loss: 0.7368
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.6279 - val_accuracy: 0.3333 - val_loss: 0.7387
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 0.6272 - val_accuracy: 0.3333 - val_loss: 0.7372
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 0.6270 - val_accuracy: 0.3333 - val_loss: 0.7358
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.6264 - val_accuracy: 0.3333 - val_loss: 0.7379
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6667 - loss: 0.6256 - val_accuracy: 0.3333 - val_loss: 0.7364
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6667 - loss: 0.6251 - val_accuracy: 0.3333 - val_loss: 0.7385
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6667 - loss: 0.6247 - val_accuracy: 0.3333 - val_loss: 0.7405
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.6249 - val_accuracy: 0.3333 - val_loss: 0.7424
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 0.6220 - val_accuracy: 0.3333 - val_loss: 0.7441
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6667 - loss: 0.6210 - val_accuracy: 0.3333 - val_loss: 0.7433
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.6201 - val_accuracy: 0.3333 - val_loss: 0.7450
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6667 - loss: 0.6195 - val_accuracy: 0.3333 - val_loss: 0.7431
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6667 - loss: 0.6196 - val_accuracy: 0.3333 - val_loss: 0.7451
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 0.6181 - val_accuracy: 0.3333 - val_loss: 0.7472
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 0.6174 - val_accuracy: 0.3333 - val_loss: 0.7463
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6667 - loss: 0.6165 - val_accuracy: 0.3333 - val_loss: 0.7479
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 0.6156 - val_accuracy: 0.3333 - val_loss: 0.7496
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6667 - loss: 0.6154 - val_accuracy: 0.3333 - val_loss: 0.7516
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6667 - loss: 0.6144 - val_accuracy: 0.3333 - val_loss: 0.7536
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6667 - loss: 0.6130 - val_accuracy: 0.3333 - val_loss: 0.7526
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6667 - loss: 0.6121 - val_accuracy: 0.3333 - val_loss: 0.7517
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.6113 - val_accuracy: 0.3333 - val_loss: 0.7535
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6667 - loss: 0.6118 - val_accuracy: 0.3333 - val_loss: 0.7554
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6667 - loss: 0.6092 - val_accuracy: 0.3333 - val_loss: 0.7573
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.6085 - val_accuracy: 0.3333 - val_loss: 0.7590
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 0.6071 - val_accuracy: 0.3333 - val_loss: 0.7610
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6667 - loss: 0.6063 - val_accuracy: 0.3333 - val_loss: 0.7629
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.6667 - loss: 0.6054 - val_accuracy: 0.3333 - val_loss: 0.7619
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.6667 - loss: 0.6044 - val_accuracy: 0.3333 - val_loss: 0.7636
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6667 - loss: 0.6038 - val_accuracy: 0.3333 - val_loss: 0.7611
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6667 - loss: 0.6032 - val_accuracy: 0.3333 - val_loss: 0.7599
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.6021 - val_accuracy: 0.3333 - val_loss: 0.7617
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.6667 - loss: 0.6023 - val_accuracy: 0.3333 - val_loss: 0.7595
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.6667 - loss: 0.6011 - val_accuracy: 0.3333 - val_loss: 0.7614
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6667 - loss: 0.5998 - val_accuracy: 0.3333 - val_loss: 0.7632
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6667 - loss: 0.5993 - val_accuracy: 0.3333 - val_loss: 0.7606
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.6667 - loss: 0.5987 - val_accuracy: 0.3333 - val_loss: 0.7594
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6667 - loss: 0.5980 - val_accuracy: 0.3333 - val_loss: 0.7573
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.5975 - val_accuracy: 0.3333 - val_loss: 0.7552
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.5970 - val_accuracy: 0.3333 - val_loss: 0.7568
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 0.5959 - val_accuracy: 0.3333 - val_loss: 0.7587
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 0.5951 - val_accuracy: 0.3333 - val_loss: 0.7576
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7778 - loss: 0.5942 - val_accuracy: 0.3333 - val_loss: 0.7596
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6667 - loss: 0.5930 - val_accuracy: 0.3333 - val_loss: 0.7585
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7778 - loss: 0.5923 - val_accuracy: 0.3333 - val_loss: 0.7560
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7778 - loss: 0.5928 - val_accuracy: 0.3333 - val_loss: 0.7535
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7778 - loss: 0.5916 - val_accuracy: 0.3333 - val_loss: 0.7515
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7778 - loss: 0.5909 - val_accuracy: 0.3333 - val_loss: 0.7532
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7778 - loss: 0.5904 - val_accuracy: 0.3333 - val_loss: 0.7550
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7778 - loss: 0.5889 - val_accuracy: 0.3333 - val_loss: 0.7569
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7778 - loss: 0.5883 - val_accuracy: 0.3333 - val_loss: 0.7585
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7778 - loss: 0.5869 - val_accuracy: 0.3333 - val_loss: 0.7602
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7778 - loss: 0.5862 - val_accuracy: 0.3333 - val_loss: 0.7579
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7778 - loss: 0.5856 - val_accuracy: 0.3333 - val_loss: 0.7598
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7778 - loss: 0.5849 - val_accuracy: 0.3333 - val_loss: 0.7575
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7778 - loss: 0.5844 - val_accuracy: 0.3333 - val_loss: 0.7553
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7778 - loss: 0.5839 - val_accuracy: 0.3333 - val_loss: 0.7528
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7778 - loss: 0.5836 - val_accuracy: 0.3333 - val_loss: 0.7546
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7778 - loss: 0.5824 - val_accuracy: 0.3333 - val_loss: 0.7535
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7778 - loss: 0.5820 - val_accuracy: 0.3333 - val_loss: 0.7553
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7778 - loss: 0.5803 - val_accuracy: 0.3333 - val_loss: 0.7575
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7778 - loss: 0.5794 - val_accuracy: 0.3333 - val_loss: 0.7591
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.7778 - loss: 0.5793 - val_accuracy: 0.3333 - val_loss: 0.7609
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7778 - loss: 0.5778 - val_accuracy: 0.3333 - val_loss: 0.7628
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7778 - loss: 0.5771 - val_accuracy: 0.3333 - val_loss: 0.7647
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.7778 - loss: 0.5761 - val_accuracy: 0.3333 - val_loss: 0.7618
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7778 - loss: 0.5761 - val_accuracy: 0.3333 - val_loss: 0.7637
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7778 - loss: 0.5746 - val_accuracy: 0.3333 - val_loss: 0.7658
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7778 - loss: 0.5742 - val_accuracy: 0.3333 - val_loss: 0.7630
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7778 - loss: 0.5736 - val_accuracy: 0.3333 - val_loss: 0.7645
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7778 - loss: 0.5726 - val_accuracy: 0.3333 - val_loss: 0.7663
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7778 - loss: 0.5721 - val_accuracy: 0.3333 - val_loss: 0.7676
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7778 - loss: 0.5717 - val_accuracy: 0.3333 - val_loss: 0.7690
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7778 - loss: 0.5703 - val_accuracy: 0.3333 - val_loss: 0.7702
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7778 - loss: 0.5701 - val_accuracy: 0.3333 - val_loss: 0.7718
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7778 - loss: 0.5692 - val_accuracy: 0.3333 - val_loss: 0.7730
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7778 - loss: 0.5688 - val_accuracy: 0.3333 - val_loss: 0.7742
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7778 - loss: 0.5680 - val_accuracy: 0.3333 - val_loss: 0.7703
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7778 - loss: 0.5670 - val_accuracy: 0.3333 - val_loss: 0.7716
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7778 - loss: 0.5665 - val_accuracy: 0.3333 - val_loss: 0.7688
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7778 - loss: 0.5652 - val_accuracy: 0.3333 - val_loss: 0.7655
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7778 - loss: 0.5646 - val_accuracy: 0.3333 - val_loss: 0.7670
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7778 - loss: 0.5642 - val_accuracy: 0.3333 - val_loss: 0.7685
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7778 - loss: 0.5628 - val_accuracy: 0.3333 - val_loss: 0.7698
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7778 - loss: 0.5628 - val_accuracy: 0.3333 - val_loss: 0.7713
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7778 - loss: 0.5615 - val_accuracy: 0.3333 - val_loss: 0.7688
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7778 - loss: 0.5615 - val_accuracy: 0.3333 - val_loss: 0.7648
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7778 - loss: 0.5600 - val_accuracy: 0.3333 - val_loss: 0.7616
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7778 - loss: 0.5591 - val_accuracy: 0.3333 - val_loss: 0.7629
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.7778 - loss: 0.5584 - val_accuracy: 0.3333 - val_loss: 0.7593
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7778 - loss: 0.5578 - val_accuracy: 0.3333 - val_loss: 0.7558

In [ ]:
loss, accuracy = model.evaluate(
    X_test_scaled,
    y_test
)

print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7500 - loss: 0.6433
Test Loss: 0.6432712078094482
Test Accuracy: 0.75